const CourseListConfig = [
  {
    Course_Code: 'ACC 101',
    Course_Title: 'Intro. to Acct. I',
    Course_ID: 144,
    Collection_ID: 154,
    Course_Context: 'course_144',
  },
  {
    Course_Code: 'AMS 101',
    Course_Title: 'Principles of Mgt.',
    Course_ID: 152,
    Collection_ID: 51,
    Course_Context: 'course_152',
  },
  {
    Course_Code: 'AMS 104',
    Course_Title: 'Principles of Project Mgt.',
    Course_ID: 147,
    Collection_ID: 1375,
    Course_Context: 'course_147',
  },
  {
    Course_Code: 'AMS 105',
    Course_Title: 'Basic Maths',
    Course_ID: 164,
    Collection_ID: 227,
    Course_Context: 'course_164',
  },
  {
    Course_Code: 'ANA 201',
    Course_Title: 'Anatomy of Upper and Lower Limb',
    Course_ID: 215,
    Collection_ID: 787,
    Course_Context: 'course_215',
  },
  {
    Course_Code: 'ANA 203',
    Course_Title: 'General and Systemic Embryology',
    Course_ID: 214,
    Collection_ID: 1116,
    Course_Context: 'course_214',
  },
  {
    Course_Code: 'BCH 201',
    Course_Title: 'Biochemistry – General and Medical I',
    Course_ID: 217,
    Collection_ID: 1136,
    Course_Context: 'course_217',
  },
  {
    Course_Code: 'BCH 203',
    Course_Title: 'General Biochemistry Practical 1',
    Course_ID: 223,
    Collection_ID: 1146,
    Course_Context: 'course_223',
  },
  {
    Course_Code: 'BIO 101',
    Course_Title: 'General Biology I',
    Course_ID: 227,
    Collection_ID: 773,
    Course_Context: 'course_227',
  },
  {
    Course_Code: 'BIO 102',
    Course_Title: 'General Biology II',
    Course_ID: 399,
    Collection_ID: 2021,
    Course_Context: 'course_399',
  },
  {
    Course_Code: 'BIO 107',
    Course_Title: 'General Biology Practical I',
    Course_ID: 229,
    Collection_ID: 1141,
    Course_Context: 'course_229',
  },
  {
    Course_Code: 'BIO 108',
    Course_Title: 'General Biology Practical II',
    Course_ID: 228,
    Collection_ID: 2022,
    Course_Context: 'course_228',
  },
  {
    Course_Code: 'BUA 101',
    Course_Title: 'Intro. to Business I',
    Course_ID: 154,
    Collection_ID: 242,
    Course_Context: 'course_154',
  },
  {
    Course_Code: 'CHM 101',
    Course_Title: 'General Chemistry I',
    Course_ID: 231,
    Collection_ID: 910,
    Course_Context: 'course_231',
  },
  {
    Course_Code: 'CHM 102',
    Course_Title: 'General Chemistry II',
    Course_ID: 233,
    Collection_ID: 2023,
    Course_Context: 'course_233',
  },
  {
    Course_Code: 'CHM 107',
    Course_Title: 'General Chemistry Practical I',
    Course_ID: 232,
    Collection_ID: 1135,
    Course_Context: 'course_232',
  },
  {
    Course_Code: 'CHM 108',
    Course_Title: 'General Chemistry Practical II',
    Course_ID: 234,
    Collection_ID: 2024,
    Course_Context: 'course_234',
  },
  {
    Course_Code: 'CSC 101',
    Course_Title: 'Intro. to Computing',
    Course_ID: 163,
    Collection_ID: 44,
    Course_Context: 'course_163',
  },
  {
    Course_Code: 'ECO 101',
    Course_Title: 'Principles of Econs. I',
    Course_ID: 155,
    Collection_ID: 47,
    Course_Context: 'course_155',
  },
  {
    Course_Code: 'ECO 103',
    Course_Title: 'Intro. Maths for Economists I',
    Course_ID: 145,
    Collection_ID: 186,
    Course_Context: 'course_145',
  },
  {
    Course_Code: 'ENT 211',
    Course_Title: 'Entrepreneurship and Innovation',
    Course_ID: 213,
    Collection_ID: 1470,
    Course_Context: 'course_213',
  },
  {
    Course_Code: 'FIN 101',
    Course_Title: 'Intro. to Finance',
    Course_ID: 143,
    Collection_ID: 196,
    Course_Context: 'course_143',
  },
  {
    Course_Code: 'GST 111',
    Course_Title: 'Comm. in English I',
    Course_ID: 159,
    Collection_ID: 153,
    Course_Context: 'course_159',
  },
  {
    Course_Code: 'GST 112',
    Course_Title: 'Nigerian Peoples and Culture',
    Course_ID: 226,
    Collection_ID: 1144,
    Course_Context: 'course_226',
  },
  {
    Course_Code: 'GST 121',
    Course_Title: 'Use of Lib. Study Skills & ICT',
    Course_ID: 165,
    Collection_ID: 241,
    Course_Context: 'course_165',
  },
  {
    Course_Code: 'GST 127',
    Course_Title: 'Envir. Sustainability',
    Course_ID: 148,
    Collection_ID: 54,
    Course_Context: 'course_148',
  },
  {
    Course_Code: 'GST 125',
    Course_Title: 'Contemporary Health Issues',
    Course_ID: 153,
    Collection_ID: 152,
    Course_Context: 'course_153',
  },
  {
    Course_Code: 'MTH 101',
    Course_Title: 'Elementary Maths',
    Course_ID: 160,
    Collection_ID: 50,
    Course_Context: 'course_160',
  },
  {
    Course_Code: 'NSC 201',
    Course_Title: 'Foundation of Professional Nursing Practice I',
    Course_ID: 218,
    Collection_ID: 1143,
    Course_Context: 'course_218',
  },
  {
    Course_Code: 'NSC 203',
    Course_Title: 'Developmental Psychology',
    Course_ID: 219,
    Collection_ID: 1286,
    Course_Context: 'course_219',
  },
  {
    Course_Code: 'PAD 101',
    Course_Title: 'Elements of Public Administration',
    Course_ID: 142,
    Collection_ID: 184,
    Course_Context: 'course_142',
  },
  {
    Course_Code: 'PAD 103',
    Course_Title: 'Elements of Govt.',
    Course_ID: 157,
    Collection_ID: 185,
    Course_Context: 'course_157',
  },
  {
    Course_Code: 'PAS 104',
    Course_Title: 'Intro. of Public Admin.',
    Course_ID: 151,
    Collection_ID: 2025,
    Course_Context: 'course_151',
  },
  {
    Course_Code: 'PHY 101',
    Course_Title: 'General Phy. I',
    Course_ID: 146,
    Collection_ID: 209,
    Course_Context: 'course_146',
  },
  {
    Course_Code: 'PHY 102',
    Course_Title: 'General Physics II',
    Course_ID: 238,
    Collection_ID: 1138,
    Course_Context: 'course_238',
  },
  {
    Course_Code: 'PHY 108',
    Course_Title: 'General Physics Practical II',
    Course_ID: 240,
    Collection_ID: 1567,
    Course_Context: 'course_240',
  },
  {
    Course_Code: 'PHY 107',
    Course_Title: 'General Practical Physics 1',
    Course_ID: 156,
    Collection_ID: 234,
    Course_Context: 'course_156',
  },
  {
    Course_Code: 'PIO 201',
    Course_Title: 'Intro Physiology and Blood',
    Course_ID: 216,
    Collection_ID: 1124,
    Course_Context: 'course_216',
  },
  {
    Course_Code: 'POL 101',
    Course_Title: 'Intro. to Political Science',
    Course_ID: 161,
    Collection_ID: 195,
    Course_Context: 'course_161',
  },
  {
    Course_Code: 'PSY 101',
    Course_Title: 'Intro. to Psychology',
    Course_ID: 149,
    Collection_ID: 1140,
    Course_Context: 'course_149',
  },
  {
    Course_Code: 'SOC 101',
    Course_Title: 'Intro. to Sociology',
    Course_ID: 150,
    Collection_ID: 205,
    Course_Context: 'course_150',
  },
  {
    Course_Code: 'SSC 101',
    Course_Title: 'Introductory Stats. I',
    Course_ID: 162,
    Collection_ID: 49,
    Course_Context: 'course_162',
  },
  {
    Course_Code: 'COS 102',
    Course_Title: 'Introduction to Problem Solving',
    Course_ID: 187,
    Collection_ID: 1170,
    Course_Context: 'course_187',
  },
  {
    Course_Code: 'GST 122',
    Course_Title: 'Communication in English Language II',
    Course_ID: 273,
    Collection_ID: 1118,
    Course_Context: 'course_273',
  },
  {
    Course_Code: 'MTH 102',
    Course_Title: 'Elementary Math (Calculus) II',
    Course_ID: 247,
    Collection_ID: 855,
    Course_Context: 'course_247',
  },
  {
    Course_Code: 'BUA 102',
    Course_Title: 'Introduction to Business II',
    Course_ID: 255,
    Collection_ID: 1117,
    Course_Context: 'course_255',
  },
  {
    Course_Code: 'ACC 102',
    Course_Title: 'Introduction to Financial Accounting II',
    Course_ID: 249,
    Collection_ID: 1149,
    Course_Context: 'course_249',
  },
  {
    Course_Code: 'ECO 104',
    Course_Title: 'Introductory Math for Economists II',
    Course_ID: 251,
    Collection_ID: 1139,
    Course_Context: 'course_251',
  },
  {
    Course_Code: 'ECO 106',
    Course_Title: 'Introductory Statistics II',
    Course_ID: 252,
    Collection_ID: 1282,
    Course_Context: 'course_252',
  },
  {
    Course_Code: 'ECO 102',
    Course_Title: 'Principles of Economics II',
    Course_ID: 250,
    Collection_ID: 1137,
    Course_Context: 'course_250',
  },
  {
    Course_Code: 'AMS 104',
    Course_Title: 'Principles of Management II',
    Course_ID: 274,
    Collection_ID: 865,
    Course_Context: 'course_274',
  },
  {
    Course_Code: 'CSC 106',
    Course_Title: 'Introduction to Web Technologies',
    Course_ID: 269,
    Collection_ID: 1145,
    Course_Context: 'course_269',
  },
  {
    Course_Code: 'CSC 208',
    Course_Title: 'User Testing Course',
    Course_ID: 208,
    Collection_ID: 0,
    Course_Context: 'course_208',
  },
];

export { CourseListConfig };
